name: iOS Build - Final

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build-ios:
    runs-on: macos-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm install --legacy-peer-deps
      
    - name: Setup Expo
      run: npm install -g @expo/cli
      
    - name: Prebuild iOS
      run: npx expo prebuild --platform ios --clean
      
    - name: Verify iOS directory
      run: |
        ls -la ios/
        echo "iOS directory created successfully"
        
    - name: Build iOS app for simulator
      run: |
        cd ios
        xcodebuild -workspace SENTINAL.xcworkspace \
                   -scheme SENTINAL \
                   -configuration Release \
                   -destination 'platform=iOS Simulator,name=iPhone 15,OS=latest' \
                   -archivePath SENTINAL.xcarchive \
                   archive
                   
    - name: Export IPA for simulator
      run: |
        cd ios
        xcodebuild -exportArchive \
                   -archivePath SENTINAL.xcarchive \
                   -exportPath ./build \
                   -exportOptionsPlist ExportOptions.plist
                   
    - name: Create ExportOptions.plist
      run: |
        cd ios
        cat > ExportOptions.plist << EOF
        <?xml version="1.0" encoding="UTF-8"?>
        <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
        <plist version="1.0">
        <dict>
            <key>method</key>
            <string>development</string>
            <key>teamID</key>
            <string></string>
            <key>compileBitcode</key>
            <false/>
            <key>uploadBitcode</key>
            <false/>
            <key>uploadSymbols</key>
            <false/>
            <key>signingStyle</key>
            <string>automatic</string>
        </dict>
        </plist>
        EOF
        
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ios-build
        path: ios/build/
        retention-days: 30
        
    - name: Build summary
      run: |
        echo "✅ iOS build completed successfully!"
        echo "📱 App built for iOS Simulator"
        echo "📦 Artifacts uploaded and available for download"
